#!/bin/bash

# read text symbols from libclang_rt.asan*.so file and
# create the map files accordingly.

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <lib_file> <map_file>"
    exit 1
fi

lib_file=$1
map_file=$2

echo Creating $map_file from $lib_file
nm -g --defined-only $lib_file | \
  awk 'BEGIN { print "# AUTO-GENERATED by update_map_files.sh. DO NOT EDIT.\nLIBCLANG_RT_ASAN {\n  global:"}\
       {if ($2 == "T" || $2 == "W" || $2 == "B") {printf "    %s;\n",$3}}\
       END { print "  local:\n    *;\n};"}'\
  > $map_file
echo Done.
